### ISSUE TITLE
RSTP creates temporary loops

### ISSUE THREAD

**Issue by jacekkow** [mstpd/mstpd#100] opened 2020-09-17 22:55 UTC
I have installed mstpd on a Debian 10 system which has a bridge (interface name is, conveniently, `bridge`) with two bonds attached (`bond-sw1`=`enp9s0f0`+`enp9s0f1` and `bond-sw2`=`enp9s0f2`+`enp9s0f3`), which are connected to two different switches running RSTP.

Everything seems to work:
```
# mstpctl showbridge bridge
bridge CIST info
  enabled         yes
  bridge id       8.000.00:...:22
  designated root 5.000.C4:...:A8
  regional root   8.000.00:...:22
  root port       bond-sw2 (#2)
  path cost     1000       internal path cost   0
  max age       20         bridge max age       20
  forward delay 15         bridge forward delay 15
  tx hold count 6          max hops             20
  hello time    2          ageing time          300
  force protocol version     rstp
  time since topology change 967s
  topology change count      4
  topology change            no
  topology change port       bond-sw2
  last topology change port  bond-sw1
# cat /sys/class/net/bridge/bridge/stp_state
2
```
But when I reboot one of the switches (being the root in RSTP tree, connected to `bond-sw2`), once it starts system shows that for a short period of time there is a loop present!
```
[  840.471477] bridge: received packet on bond-sw2 with own address as source address (addr:00:..:22, vlan:0)
[  840.471605] bridge: received packet on bond-sw2 with own address as source address (addr:00:..:22, vlan:0)
[  840.471720] bridge: received packet on bond-sw2 with own address as source address (addr:00:..:22, vlan:0)
```
(full [dmesg.log](https://github.com/mstpd/mstpd/files/5242301/dmesg.log) is attached)

It seems that mstpd allowed both bond-sw1 and bond-sw2 to enter forwarding state at once. My understanding is that RSTP should prevent occurrence of such an issue.

Could you point me as to why it happened? Scenario passes (no loops visible) with kernel's RTP.

**Comment by commodo** [comment] 2020-09-18 09:23
A lot of link flapping is present in those dmest logs.
Maybe you would need to tune some of the forward delays?
```
  forward delay 15         bridge forward delay 15
```

**Comment by commodo** [comment] 2021-09-30 07:33
Any more input here?
Will close this for now.

Feel free to re-open if issue still exists.

Generally speaking, if the link flags (as it is in the log), some temporary loops may occur.
Now, I have no idea why this happens here (in this log)

**Closed by commodo** 2021-09-30 07:33 UTC

**Comment by ErikHons** [comment] 2023-08-30 14:14
I have seen this behavior and think I have root cause. The mstpd event loop drives all timed events using a tick tied to the monotonic clock. As a result, the 3 tick AutoEdge transition can complete in 2 seconds which is the standard hello time. If a port comes up at just the wrong time -- late in a tick -- the edge transition can occur just before a BPDU is received from the peer. The result is a brief loop until mstpd processes the BPDU.
